feature(alert): remove deprecated TerraAlertComponent
plentymarkets/terra-components pull request #1171
Opened 2020-04-21 07:50 UTC by pweyrich

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing
- [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components and jQuery)
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
    
    Responsiveness
    - [ ] Desktop
    - [ ] Tablet
    - [ ] Mobile
    
- [ ] Person 2 (mandatory)

    Browser-Support
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
    
    Responsiveness
    - [ ] Desktop
    - [ ] Tablet
    - [ ] Mobile

Terra Basic Plugin
- [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

----

#### Must be done by every developer
Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline). 

Documentation
- [ ] Changelog (optional: relevant for every change which influences the API)
- [ ] Example (updated or created)
- [ ] JSDoc (optional: relevant for every change which influences the API)

Testing
- [ ] Unit Test (updated or created)

2020-04-22 20:39 UTC, pweyrich commented
Alerts in der TerraAlertPanelComponent

2020-12-29 12:57 UTC, dantrau requested changes

2020-12-29 12:57 UTC, dantrau commented on src/lib/components/forms/input/terra-input.component.ts
> +                        // TODO: is this really needed????
sollte noch geklärt werden

2020-12-29 12:57 UTC, dantrau commented on src/lib/components/forms/input/terra-input.component.ts
> +                        // TODO: is this really needed???
sollte noch geklärt werden

2020-12-29 14:04 UTC, dantrau commented on src/lib/components/forms/input/terra-input.component.ts
> +                        // TODO: is this really needed????
das könnte drin bleiben, da die Component mit dem nächsten Major Release komplett entfernt wird

2020-12-29 14:04 UTC, dantrau commented on src/lib/components/forms/input/terra-input.component.ts
> +                        // TODO: is this really needed???
das könnte drin bleiben, da die Component mit dem nächsten Major Release komplett entfernt wird

2021-01-05 07:31 UTC, pweyrich commented on src/lib/components/forms/input/terra-input.component.ts
> +                        // TODO: is this really needed???
Das Problem ist nur, dass das nicht ohne eine riesige Änderung bei den Inputs realisiert werden kann mit dem AlertService.

2021-01-05 07:35 UTC, pweyrich commented on src/lib/components/alert/terra-alert-panel.component.spec.ts
> +    });
Falls Zugriff auf das von der TerraAlertComponent erzeugt DOM notwendig ist, sollte hier ein TestingModule genutzt werden.

2021-01-05 09:23 UTC, dantrau commented on src/lib/components/alert/terra-alert-panel.component.spec.ts
> +        tick(1000);
warum dieser Wert und nicht der `defaultTimeout`?

2021-01-05 09:25 UTC, pweyrich commented on src/lib/components/alert/terra-alert-panel.component.spec.ts
> +        tick(1000);
Einfach um eine zeitliche Differenz bei der Erstellung der zwei Alerts zu haben. Sonst würden nach dem defaultTimeout beide Alerts verschwinden.

2021-01-05 09:26 UTC, pweyrich commented on src/lib/components/alert/terra-alert-panel.component.spec.ts
> +        tick(1000);
Aber ggf. kann ich einfach eine info und einen error Alert erstellen. Der Error Alert wird nämlich nicht auto dismissed.. Dann passt es auch und ich brauche keine extra zeit verstreichen lassen

2021-01-05 10:18 UTC, pweyrich commented on src/lib/components/forms/input/terra-input.component.ts
> +                        // TODO: is this really needed????
alert fliegt raus da nicht mehr möglich.

2021-01-06 08:26 UTC, pweyrich commented on src/lib/components/alert/terra-alert-panel.component.spec.ts
> +        tick(1000);
done

2021-01-06 09:31 UTC, TimWieder approved these changes

2021-01-06 14:25 UTC, dantrau approved these changes

2021-01-07 09:08 UTC, merged