feature (tag and tag-list): remove all occurrences of onCloseTag and adapt unit test
plentymarkets/terra-components pull request #1392
Opened 2020-10-26 13:20 UTC by dantrau

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)
-   [ ] Person 2 (mandatory)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2020-10-26 13:25 UTC, pweyrich submitted a review, later dismissed

2020-10-26 13:26 UTC, pweyrich commented
Diese PRs gerne gleich gegen 6.X.X. Dann werden auch die checks durchlaufen.

2020-10-26 13:26 UTC, pweyrich approved these changes

2020-10-26 13:27 UTC, pweyrich requested changes
Changelog fehlt

2020-10-26 13:45 UTC, pweyrich submitted a review, later dismissed

2020-10-26 14:53 UTC, pweyrich approved these changes

2020-10-27 07:37 UTC, ChristianMoll approved these changes

2020-10-27 09:10 UTC, ChristianMoll approved these changes

2020-10-27 09:28 UTC, pweyrich commented on CHANGELOG.md
> +-   **terra-tag** removed deprecated `onCloseTag` method.
```suggestion
-   **terra-tag** removed deprecated `onCloseTag` output.
```

2020-10-27 09:28 UTC, pweyrich commented on CHANGELOG.md
> +-   **terra-taglist** removed deprecated `onCloseTag` method.
```suggestion
-   **terra-taglist** removed deprecated `onCloseTag` output.
```

2020-10-27 09:30 UTC, pweyrich approved these changes

2020-10-27 09:33 UTC, ChristianMoll approved these changes

2020-10-27 09:35 UTC, merged