feature(angular-l10n): update angular-l10n to version 9.3.0
plentymarkets/terra-components pull request #1405
Opened 2020-10-27 14:09 UTC by MFrank84

2020-10-29 07:51 UTC, Neill83 requested changes

2020-10-29 07:51 UTC, Neill83 commented on CHANGELOG.md
> +    -   changed peer dependency `mydatepicker`to require version 9.
hier ist doppelt

2020-10-29 07:51 UTC, Neill83 commented on src/app/translation/user-language.ts
> +                    browserLanguage = navigator.language.split('-')[0];
wir können hier nicht die BrowserLanguage nehmen, denn wir haben ja keinen Support für andere Sprachen...

ich würde hier einfach nur die aus dem LocalStorage nehmen und wenn nicht existiert, dann halt Englisch

2020-10-29 08:35 UTC, Neill83 approved these changes

2020-10-29 08:37 UTC, TimWieder approved these changes

2020-10-29 10:00 UTC, TimWieder submitted a review, later dismissed

2020-11-10 11:12 UTC, pweyrich commented on src/app/translation/user-language.ts
> +        return Promise.resolve(langInLocalStorage);
```suggestion
        return Promise.resolve(lang);
```

2020-11-10 11:12 UTC, pweyrich commented on src/app/translation/user-language.ts
> +import { StringHelper } from '../../lib/helpers';
import kann raus
```suggestion
```

2020-11-10 11:27 UTC, TimWieder approved these changes

2020-11-10 12:44 UTC, Neill83 approved these changes

2020-11-10 12:56 UTC, merged