feature(deps): angular 9
plentymarkets/terra-components pull request #1413
Opened 2020-10-28 10:37 UTC by pweyrich

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2020-10-29 14:56 UTC, dantrau requested changes

2020-10-29 14:56 UTC, dantrau commented on CHANGELOG.md
> +    -   changed peer dependency `mydatepicker`to require version 9
```suggestion
    -   changed peer dependency `mydatepicker` to require version 9
```

2020-10-29 14:56 UTC, dantrau commented on CHANGELOG.md
> +-   **public-api** removed examples from the public api
```suggestion
-   **public-api** removed examples from the public api.
```

2020-10-29 15:12 UTC, MFrank84 submitted a review, later dismissed

2020-10-29 16:02 UTC, dantrau requested changes
es gibt noch folgenden Fehler in der Browser Console
![Bildschirmfoto 2020-10-29 um 17 00 13](https://user-images.githubusercontent.com/21104139/97599517-60bd2080-1a08-11eb-9a9c-d799e8073552.png)
das lies sich zurückverfolgen darauf, dass `public set inputFormFields` `_updateFieldVisibility()` aufruft und zu dem Zeitpunkt inputScope noch nicht gesetzt ist

2020-10-30 08:22 UTC, ChristianMoll submitted a review, later dismissed

2020-10-30 09:24 UTC, dantrau submitted a review, later dismissed

2020-10-30 09:25 UTC, dantrau commented
> es gibt noch folgenden Fehler in der Browser Console
> ![Bildschirmfoto 2020-10-29 um 17 00 13](https://user-images.githubusercontent.com/21104139/97599517-60bd2080-1a08-11eb-9a9c-d799e8073552.png)
> das lies sich zurückverfolgen darauf, dass `public set inputFormFields` `_updateFieldVisibility()` aufruft und zu dem Zeitpunkt inputScope noch nicht gesetzt ist

der Fehler ist wieder weg 😕

2020-10-30 10:43 UTC, pweyrich commented on CHANGELOG.md
> +-   **public-api** removed examples from the public api.
```suggestion
-   **public-api** removed `TerraComponentsExamplesModule` from the public api.
```

2020-10-30 10:43 UTC, dantrau submitted a review, later dismissed

2020-10-30 11:01 UTC, dantrau approved these changes

2020-10-30 11:29 UTC, ChristianMoll approved these changes

2020-10-30 12:27 UTC, Neill83 approved these changes

2020-10-30 12:27 UTC, MFrank84 approved these changes

2020-10-30 12:27 UTC, merged