feature(deps): update karma & jasmine
plentymarkets/terra-components pull request #1424
Opened 2020-10-29 09:47 UTC by dantrau

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)
-   [ ] Person 2 (mandatory)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)

Testing

-   [ ] Unit Test (updated or created)

2020-11-20 09:32 UTC, pweyrich approved these changes
👍

2020-12-22 06:43 UTC, Neill83 approved these changes

2020-12-22 06:46 UTC, Neill83 requested changes
Changelog fehlt

2020-12-23 07:00 UTC, Neill83 approved these changes

2020-12-23 07:35 UTC, MFrank84 approved these changes

2020-12-23 08:25 UTC, Neill83 commented on CHANGELOG.md
> +# 6.0.0-alpha.6 (DD.MM.YYYY)
```suggestion
# 6.0.0-alpha.X (DD.MM.YYYY)
```

2020-12-23 08:26 UTC, Neill83 approved these changes

2020-12-23 08:27 UTC, MFrank84 approved these changes

2020-12-23 08:36 UTC, merged