feature(StringHelper): remove deprecated util function
plentymarkets/terra-components pull request #1433
Opened 2020-11-09 14:25 UTC by dantrau

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)
-   [ ] Person 2 (mandatory)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)

Testing

-   [ ] Unit Test (updated or created)

2020-11-09 15:47 UTC, zhajjhassan approved these changes

2020-12-22 07:36 UTC, Neill83 requested changes
Changelog fehlt

2020-12-22 07:36 UTC, Neill83 commented on src/lib/helpers/tests/string.helper.spec.ts
>          expect(StringHelper.isNullUndefinedOrEmpty(testVar)).toBe(true);
```suggestion
        expect(StringHelper.isNullUndefinedOrEmpty(testVar)).toBeTrue();
```

2020-12-22 07:36 UTC, Neill83 commented on src/lib/helpers/tests/string.helper.spec.ts
>          expect(StringHelper.isNullUndefinedOrEmpty(testVar)).toBe(true);
wenn es die Methoden gibt, kann man die ja bestimmt verwenden, oder? :)

2020-12-22 09:34 UTC, MFrank84 requested changes
Changelog fehlt

2020-12-23 06:56 UTC, Neill83 approved these changes

2020-12-23 07:38 UTC, MFrank84 approved these changes

2020-12-23 08:44 UTC, Neill83 approved these changes

2020-12-23 08:45 UTC, MFrank84 approved these changes

2020-12-23 08:58 UTC, merged