replace terra button with mat button
plentymarkets/terra-components pull request #1439
Opened 2020-11-25 21:50 UTC by ChristianMoll

@plentymarkets/team-terra

2020-11-26 08:03 UTC, TimWieder submitted a review, later dismissed

2020-11-26 09:40 UTC, pweyrich commented on src/lib/components/table/table-settings/table-settings.component.html
> +    [matTooltip]="'cms.shopBuilder.content.backupTable.cantRestore' | translate: _locale.language"
bitte nicht den MatTooltip verwenden. Stattdessen unseren `tcTooltip` benutzen!

2020-11-26 09:40 UTC, pweyrich commented on src/lib/components/table/table-settings/table-settings.component.html
> +    [matTooltip]="'cms.shopBuilder.content.backupTable.cantRestore' | translate: _locale.language"
Außerdem ist der Übersetzungskey falsch^^

2020-11-27 05:44 UTC, TimWieder approved these changes

2020-11-27 10:33 UTC, Neill83 approved these changes

2020-11-30 07:57 UTC, Neill83 requested changes
changelog

2020-11-30 12:29 UTC, zakpur submitted a review, later dismissed

2020-11-30 12:45 UTC, TimWieder approved these changes

2020-11-30 13:08 UTC, zakpur approved these changes

2020-11-30 13:17 UTC, merged