feature(table settings): enable scrolling up/down while dragging an item
plentymarkets/terra-components pull request #1441
Opened 2020-11-26 14:24 UTC by MFrank84

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2020-11-27 05:44 UTC, TimWieder submitted a review, later dismissed

2020-11-30 07:40 UTC, Neill83 requested changes
changelog

2020-11-30 08:13 UTC, Neill83 commented
![image](https://user-images.githubusercontent.com/9987324/100584374-4e2a5580-32ec-11eb-9868-2f56550d6859.png)
man hat 2 Scrollbalken... weiß jetzt nicht ob das so schön ist

2020-11-30 11:55 UTC, zakpur submitted a review, later dismissed

2020-11-30 11:56 UTC, TimWieder approved these changes

2020-11-30 13:39 UTC, zakpur approved these changes

2020-11-30 14:11 UTC, Neill83 approved these changes

2020-11-30 14:11 UTC, zakpur approved these changes

2020-11-30 14:15 UTC, merged