added link to code-editor toolbar
plentymarkets/terra-components pull request #1446
Opened 2020-12-01 11:12 UTC by maxiroellplenty

@plentymarkets/team-terra
@plentymarkets/ceres-io 

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2020-12-10 14:40 UTC, Tim-M-S approved these changes

2020-12-11 12:22 UTC, pweyrich requested changes

2020-12-11 12:22 UTC, pweyrich commented on CHANGELOG.md
> +-   **terra-code-editor** toolbar now supports links.
alpha.4 wurde bereits released. Du müsstest also eine neue Section erstellen.

2020-12-14 10:36 UTC, pweyrich submitted a review, later dismissed
tested 👍

2020-12-14 10:54 UTC, pweyrich approved these changes

2020-12-15 10:52 UTC, dantrau approved these changes

2020-12-15 14:41 UTC, merged