feature(terra-slider): remove deprecated inputValue and inputValueChange
plentymarkets/terra-components pull request #1452
Opened 2020-12-22 07:46 UTC by MFrank84

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2020-12-22 08:01 UTC, Neill83 approved these changes

2020-12-22 14:15 UTC, dantrau requested changes

2020-12-22 14:15 UTC, dantrau commented on src/lib/components/forms/slider/example/terra-slider.component.example.html
> -        <div class="col-md-6">
warum hast du das Beispiel entfernt?
2-Way-Data-Binding geht ja weiterhin
oder hatte das den ExpressionHasChanged.... Fehler verursacht?

2020-12-22 14:17 UTC, MFrank84 commented on src/lib/components/forms/slider/example/terra-slider.component.example.html
> -        <div class="col-md-6">
Das ist das 2-Way-Data-Binding für `inputValue`, darunter ist dann das Beispiel für `ngModel`

2020-12-22 15:13 UTC, dantrau approved these changes

2020-12-23 07:32 UTC, Neill83 commented on src/lib/components/forms/slider/example/terra-slider.component.example.html
> -        <div class="col-md-6">
es gibt auch ein Beispiel (da drunter) für 2-Way-Data-Binding mit ngModel

2020-12-23 07:36 UTC, merged