Feature/route data/get children
plentymarkets/terra-components pull request #1493
Opened 2021-02-11 13:11 UTC by TimWieder

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2021-02-11 14:01 UTC, pweyrich commented on src/lib/route-data/utils/route-children-function.ts
> +export function getChildren(route: Route): Routes {
Macht einfach noch deutlicher was zurück kommen kann.
Wird im Strict mode dann auch pflicht sein.

2021-02-12 06:16 UTC, TimWieder commented on src/lib/route-data/utils/index.ts
> +export * from './route-children-function';
Ich finde es passt da besser hin, weil es zum Route-Thema passt. Wäre also eher dafür den Ordner vielleicht allgemeiner zu nennen

2021-02-12 10:27 UTC, Neill83 commented on src/lib/route-data/utils/index.ts
> +export * from './route-children-function';
ich würde es dann so aufbauen

```
- route
   - data
        - utils
   - utils
```

2021-02-12 10:29 UTC, Neill83 requested changes

2021-02-12 10:29 UTC, Neill83 commented on CHANGELOG.md
> +-   **route-children-function** implemented getChild() function which returns the children to a route with it's children
```suggestion
-   **route-children-function** implemented `getChildren()` function which returns the children of a given route wether they are lazy loaded or not.
```

2021-02-15 07:31 UTC, MFrank84 requested changes

2021-02-15 07:31 UTC, MFrank84 commented on CHANGELOG.md
> +-   **route-children-function** implemented `getChildren()` function which returns the children of a given route wether they are lazy loaded or not.
```suggestion
-   **route-children-function** implemented `getChildren()` function which returns the children of a given route wether they are lazy loaded or static.
```

2021-02-15 07:31 UTC, MFrank84 commented on src/lib/route-data/utils/index.ts
> +export * from './route-children-function';
Das von Kunze find ich gut, da wäre es aber auch eine Idee den ActiveRouteHelper aufzulösen und die enthaltene Funktion auch als "Util Function" anzubieten (unter route/utlis)

2021-02-15 09:42 UTC, pweyrich commented on CHANGELOG.md
> +-   **route-children-function** implemented `getChildren()` function which returns the children of a given route wether they are lazy loaded or static.
```suggestion
-   **route** implemented `getChildren()` function which returns the children of a given route whether they are lazy loaded or static.
```

2021-02-15 09:42 UTC, pweyrich commented on src/lib/public-api.ts
> +export * from './route/data';
hier sollte dann alles aus der index.ts im `route` ordner exportiert werden.
```suggestion
export * from './route';
```

2021-02-15 09:42 UTC, pweyrich commented on src/lib/route/data/index.ts
> +export { extractRouteDataFromRouterConfig, findMatchingRoutePath, getChildren } from '../utils';
das sollte hier raus und in die `utils/index.ts`

2021-02-15 09:42 UTC, pweyrich commented on src/lib/route/index.ts
> +export * from './data';
Wir müssen schauen, ob wir hier wirklich alles exportieren wollen. Ich denke es wäre sinnvoll hier nur punktuell zu exportieren, da diese datei dann im gesamten in der public-api landet.

2021-02-15 09:42 UTC, pweyrich commented on src/lib/route/utils/route-children-function.ts
> +export function getChildren(route: Route): Routes | undefined {
Ein kleiner aber feiner Unit-Test fehlt noch.

2021-02-15 09:42 UTC, pweyrich commented on src/lib/route/utils/route-children-function.ts
> + * This function returns the children of a given route wether they are lazy loaded or not
```suggestion
 * This function returns the children of a given route regardless they are eagerly or lazy loaded.
```

2021-02-15 10:51 UTC, pweyrich commented on src/lib/route/index.ts
> +    compareSegments,
Ich denke das kann eine private api bleiben

2021-02-15 10:51 UTC, pweyrich commented on src/lib/route/index.ts
> +    normalizeRoutePath,
diese auch.

2021-02-15 10:51 UTC, pweyrich commented on src/lib/route/utils/route-children-function.spec.ts
> +        route['_loadedConfig'] = { routes: [{ path: 'bar', data: { label: 'bar' } }] };
```suggestion
        const route: Route = {
            path: 'foo',
            '_loadedConfig': { routes: [{ path: 'bar', data: { label: 'bar' } }] }
        };
```

2021-02-15 10:51 UTC, pweyrich commented on src/lib/route/utils/route-children-function.spec.ts
> +        expect(getChildren(route)).toEqual([{ path: 'bar', data: { label: 'bar' } }]);
```suggestion
        expect(getChildren(route)).toBe(route.children);
```

2021-02-15 10:51 UTC, pweyrich commented on CHANGELOG.md
> +# 6.0.1 Unreleased
```suggestion
# 6.1.0 Unreleased
```
Ist ja nen Feature also ein Minor-Release

2021-02-15 10:51 UTC, pweyrich commented on src/lib/route/utils/route-children.spec.ts
> +        expect(getChildren(route)).toEqual([{ path: 'bar', data: { label: 'bar' } }]);
```suggestion
        expect(getChildren(route)).toBe(route.children);
```

2021-02-15 10:51 UTC, pweyrich commented on src/lib/route/utils/route-children.spec.ts
> +        route['_loadedConfig'] = { routes: [{ path: 'bar', data: { label: 'bar' } }] };
```suggestion
        const route: Route = {
            path: 'foo',
            '_loadedConfig': { routes: [{ path: 'bar', data: { label: 'bar' } }] }
        };
```
Oder meckert typescript dann?

2021-02-15 10:51 UTC, pweyrich commented on src/lib/route/utils/route-children.spec.ts
> +        expect(getChildren(route)).toEqual([{ path: 'bar', data: { label: 'bar' } }]);
```suggestion
        expect(getChildren(route)).toBe(route['_loadedConfig'].routes);
```

2021-02-15 10:55 UTC, TimWieder commented on src/lib/route/utils/route-children.spec.ts
> +        route['_loadedConfig'] = { routes: [{ path: 'bar', data: { label: 'bar' } }] };
Typescript meckert dann

2021-02-15 10:56 UTC, pweyrich commented on src/lib/route/utils/route-children.spec.ts
> +        route['_loadedConfig'] = { routes: [{ path: 'bar', data: { label: 'bar' } }] };
k 👌

2021-02-15 11:00 UTC, pweyrich approved these changes

2021-02-15 11:02 UTC, MFrank84 approved these changes

2021-02-15 11:05 UTC, merged