Feature (terraForm): Creating a wrapper Component for the checkbox
plentymarkets/terra-components pull request #1542
Opened 2021-04-20 08:30 UTC by zhajjhassan

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/model/form-type-map.ts
> +            name: 'name'
in dem Fall ist kein mapping notwendig^^
Kann also komplett weg

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public value: string;
```suggestion
    public value: boolean;
```

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public _onChangeCallback: (_: string) => void = noop;
```suggestion
    public _onChangeCallback: (_: boolean) => void = noop;
```

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.html
> +    {{ name }}
Die alte Checkbox unterstützt hier noch ein icon.

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public isDisabled: boolean;
```suggestion
    public isDisabled: boolean = false;
```

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public name: string;
```suggestion
    public name: string = '';
```

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public tooltipText: string;
```suggestion
    public tooltipText: string = '';
```

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public writeValue(value: string): void {
```suggestion
    public writeValue(value: boolean): void {
```

2021-04-20 08:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public registerOnChange(fn: (_: string) => void): void {
```suggestion
    public registerOnChange(fn: (_: boolean) => void): void {
```

2021-04-20 08:54 UTC, Neill83 requested changes

2021-04-20 08:54 UTC, Neill83 commented on src/lib/components/forms/form/example/form-fields.ts
> +    defaultValue: 'true',
```suggestion
    defaultValue: 'false',
```

2021-04-20 08:54 UTC, Neill83 commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.html
> +    (blur)="_onTouchedCallback()"
blur gibts hier doch gar nicht, oder?

2021-04-20 08:54 UTC, Neill83 commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public _isIndeterminate: boolean = false;
das muss ein Input() sein, war es vorher auch

2021-04-20 08:54 UTC, Neill83 commented on src/lib/components/forms/form/example/form-fields.ts
> +        type: 'checkbox',
gibts hier keinen defaultValue?

für was ist das hier eigentlich?

2021-04-20 09:07 UTC, pweyrich commented on src/lib/components/forms/form/example/form-fields.ts
> +        type: 'checkbox',
Das ist quasi die json die im Beispiel an die TerraForm übergeben wird. Aus dieser wird dann die Form generiert.

2021-04-20 09:08 UTC, pweyrich commented on src/lib/components/forms/form/example/form-fields.ts
> +    defaultValue: 'true',
das sollte kein string sein, sondern ein boolean

2021-04-20 09:08 UTC, pweyrich commented on src/lib/components/forms/form/example/form-fields.ts
> +export const checkbox: TerraFormFieldInterface = {
Diese Konstante wird nirgends genutzt!?

2021-04-20 09:11 UTC, zhajjhassan commented on src/lib/components/forms/form/example/form-fields.ts
> +        type: 'checkbox',
das ist nur eine Erweiterung im example zum Testen

2021-04-20 09:14 UTC, pweyrich commented on src/lib/components/forms/form/model/form-type-map.ts
> +        inputMap: {},
```suggestion
```

2021-04-20 09:18 UTC, pweyrich commented on src/lib/components/forms/form/model/form-type-map.ts
> +        inputMap: {},
Mir fällt gerade auf dass wir theoretisch ein mapping für isRequired aufnehmen müssten. Den Input hatte die Checkbox bisher aber garnicht.

2021-04-20 09:37 UTC, zhajjhassan commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.html
> +    (blur)="_onTouchedCallback()"
die mat-checkbox hat eine blur Eigenschaft!

2021-04-20 09:41 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public _isIndeterminate: boolean = false;
```suggestion
    public isIndeterminate: boolean = false;
```

2021-04-20 09:42 UTC, zhajjhassan commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +    public _isIndeterminate: boolean = false;
ah copy paste!1😊

2021-04-20 09:43 UTC, pweyrich reviewed
der input `isRequired` fehlt noch.

2021-04-20 09:44 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +export class CheckboxComponent implements ControlValueAccessor {
```suggestion
export class CheckboxComponent implements ControlValueAccessor, CheckboxInterface {
```

2021-04-20 09:45 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
>      constructor() {}
Der kann raus, wenn er nicht benötigt wird.

2021-04-20 09:45 UTC, pweyrich commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.ts
> +export class CheckboxComponent implements ControlValueAccessor {
Falls das schon existiert.

2021-04-20 21:36 UTC, Neill83 requested changes

2021-04-20 21:36 UTC, Neill83 commented on src/lib/components/forms/form/model/form-type-map.ts
> +            required: 'isRequired'
was ist mit `indeterminate: 'isIndeterminate'`? müsste ja auch, oder?

2021-04-20 21:36 UTC, Neill83 commented on src/lib/components/forms/form/model/form-type-map.ts
> +            required: 'isRequired'
und was ist mit disabled - isDisabled?

2021-04-21 06:51 UTC, pweyrich commented on src/lib/components/forms/form/model/form-type-map.ts
> +            required: 'isRequired'
haben wir bisher nicht gemappt, also lassen wir es auch besser so^^

2021-04-21 07:24 UTC, niwolf commented on src/lib/components/forms/form/form-components/checkbox/checkbox.component.html
> +    (blur)="_onTouchedCallback()"
@Neill83 @zhajjhassan die mat-checkbox benachrichtigt dich  tatsächlich nicht on blur! Habe mit Pascal geschaut und wir konnten das "blur handling" durch Focus Monitoring a la angular/cdk fixen.

--> https://github.com/plentymarkets/terra-components/pull/1542/commits/a3977fa87258a1042fdbafe5e9d73829ff0ea5b7#diff-9dfd4d6125401ab5a1c8185ad44064ee26f905279e4361d4e7f95607cd866041R9-R10

2021-04-21 07:39 UTC, nappynapster approved these changes

2021-04-21 07:41 UTC, pweyrich approved these changes
sieht gut aus 👍

2021-04-21 08:25 UTC, merged