feature(form): use matInput for color picker
plentymarkets/terra-components pull request #1552
Opened 2021-04-28 19:52 UTC by nappynapster

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2021-04-30 08:22 UTC, Neill83 requested changes

2021-04-30 08:22 UTC, Neill83 commented on src/lib/components/forms/form/form-components/color-picker/color-picker.component.ts
> +        // this._onChangeCallback = fn;
```suggestion
        this._onChangeCallback = fn;
```

2021-04-30 08:22 UTC, Neill83 commented on src/lib/components/forms/form/form-components/color-picker/color-picker.component.ts
> +        // this._onTouchedCallback = fn;
```suggestion
        this._onTouchedCallback = fn;
```

2021-04-30 10:13 UTC, nappynapster commented on src/lib/components/forms/form/form-components/color-picker/color-picker.component.ts
> +        // this._onChangeCallback = fn;
habe die sachen bewusst auskommentiert, da hier die component keine Funktionalität beinhalten soll, nur die tests an sich

2021-05-03 13:58 UTC, pweyrich approved these changes
Sonst Tip top 👍

2021-05-03 13:58 UTC, pweyrich commented on src/lib/components/forms/form/form-components/color-picker/color-picker.component.spec.ts
> +    it('should call registered onTouchedCallback when select blur has been called', async () => {
```suggestion
    it('should call registered onTouchedCallback when input was blurred', async () => {
```

2021-05-03 14:21 UTC, niwolf approved these changes
👍

2021-05-03 14:48 UTC, niwolf submitted a review, later dismissed

2021-05-05 06:35 UTC, pweyrich approved these changes

2021-05-05 06:35 UTC, pweyrich commented on src/lib/components/forms/form/form-components/color-picker/color-picker.component.ts
> +    public _onChangeCallback: (_: any) => void = noop;
```suggestion
    public _onChangeCallback: (_: string) => void = noop;
```

2021-05-05 06:36 UTC, pweyrich approved these changes

2021-05-11 11:10 UTC, merged