feature (Terra Form): unit test for double input
plentymarkets/terra-components pull request #1553
Opened 2021-04-29 07:58 UTC by zhajjhassan

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser-Support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser-Support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Ceres about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2021-04-29 13:57 UTC, niwolf commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +    });
wie hier https://github.com/plentymarkets/terra-components/pull/1551#discussion_r623054165 erwähnt, denke ich nicht dass das notwenig ist, weil die Form an sich ja valid/invalid sein kann. Aber nur meine Meinung 😄

2021-04-29 14:01 UTC, niwolf commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(debugElement.nativeElement.step).toEqual(0.001);
Der Test failed. Vermutlich fehlt noch `toString()`

2021-04-30 06:25 UTC, Neill83 requested changes

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(await input.isRequired()).toBe(false);
muss das hier sein? ich denke eher nicht, wenn dann im separaten Test

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(await input.isDisabled()).toBe(false);
hier das selbe...

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(await formField.getLabel()).toBe('');
hier auch

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(await formField.getLabel()).toBe('');
mach doch einfach einen Test, der die "standard" Einstellungen testet... also nicht required, leeren Namen, etc

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +            expect(tooltip.tcTooltip).toBe('');
das auch weg

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +            expect(tooltip.placement).toBe(TerraPlacementEnum.TOP);
hier auch

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        component.writeValue(value);
hier hast du ja auch nicht geguckt, dass der Wert vorher `null` ist, oder?

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(await formField.isControlValid()).toBe(true);
auch weg

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(debugElement.styles['text-align']).toBe('left');
weg

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(debugElement.nativeElement.pattern).toEqual(TerraRegex.getDouble(2));
weg

2021-04-30 06:25 UTC, Neill83 commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(debugElement.nativeElement.step).toEqual(0.01);
weg

2021-04-30 06:38 UTC, zhajjhassan commented
hey @Neill83 , die ganzen Tests, wo du vorschlägst sie weg zu machen testen und sichern den Initialen Zustand der Inputs und Objekten. Ich finde sie gut, weil damit wird sichergestellt dass diese Initialen Zuständen erhalten bleiben und da nicht gepfusht wird. Ich verstehe nicht, was dich daran stört. Außerdem alle anderen unit tests haben wir so gemacht!

2021-04-30 06:51 UTC, pweyrich commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +            imports: [MatFormFieldModule, MatInputModule, NoopAnimationsModule, FormsModule, L10nTranslationModule],
```suggestion
            imports: [MatFormFieldModule, MatInputModule, NoopAnimationsModule, FormsModule],
```
Wird hier nicht genutzt

2021-04-30 06:51 UTC, pweyrich commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(await formField.getLabel()).toBe('');
Ich finde beide Herangehensweisen ok.

2021-04-30 06:51 UTC, pweyrich commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(debugElement.styles['text-align']).toBe('left');
Statt hier über das debugElement zu gehen, kannst du stattdessen auch hier eine Schnittstelle von @angular/material zum Testen nutzen.
Über den `host` des Inputs kommst du sowohl an die styles als auch properties ran.
Z.B.
```
const host: TestElement = await input.host();
expect(await host.getCssValue('text-align')).toBe('left');
```
Für die Properties dann respektive die `getProperty()` methode nutzen.

2021-04-30 06:53 UTC, pweyrich commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        component.writeValue(2.3422);
könnte sein, dass du hier stattdessen
```suggestion
        await input.setValue(2.3422);
```
machen müsstest.

2021-04-30 11:21 UTC, zhajjhassan commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        component.decimalCount = 3;
@pweyrich diese Anweisung hier scheint die ngOnChanges nicht zu triggern und deshalb schlägt der Test da noch fehl. Eine Idee warum das so ist?

2021-04-30 11:27 UTC, pweyrich commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        component.decimalCount = 3;
`ngOnChanges` wird vom Test nicht automatisch aufgerufen. Das müsstest du theoretisch manuell machen.
Aber die TerraForm triggert `ngOnChanges`
auch nicht. Daher hat Niklas auch die Implementierung angepasst. Aktualisiere Mal deinen Branch ;)

2021-04-30 11:39 UTC, zhajjhassan commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        expect(debugElement.nativeElement.step).toEqual(0.001);
fixed!

2021-04-30 11:41 UTC, zhajjhassan commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        component.writeValue(2.3422);
ich denke, wir brauchen es nicht, oder?

2021-04-30 12:23 UTC, pweyrich commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +        component.writeValue(2.3422);
Es gibt halt einen Unterschied. `input.setValue` gaukelt vor dass der Nutzer etwas eingibt. `component.writeValue` stattdessen würde vom Programm genutzt werden um den Wert des Inputs zu verändern.
Aber grundsätzlich sollte das control invalid sein, wenn ein falscher Wert eingetragen wird (egal welche der beiden Schnittstellen genutzt wird). 
Entsprechend kannst du es so lassen, ja :)

2021-04-30 12:24 UTC, pweyrich commented on src/lib/components/forms/form/form-components/double-input/double-input.component.spec.ts
> +    let debugElement: DebugElement;
wird nicht mehr verwendet, oder?
```suggestion
```

2021-04-30 13:24 UTC, pweyrich approved these changes

2021-04-30 13:26 UTC, niwolf approved these changes

2021-04-30 13:29 UTC, merged