feature (file-list): exchange Terra components by Material
plentymarkets/terra-components pull request #1654
Opened 2021-10-27 13:40 UTC by JanikPlenty

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Team plentyShop about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2021-11-01 08:06 UTC, Neill83 requested changes

2021-11-01 08:06 UTC, Neill83 commented on src/lib/components/file-browser/file-list/file-list.component.html
> +    <table
hier fehlt noch um die Tabelle... `<div class="terra-table-inner-container">` (in Terra gibt es eine Directive dafür)

2021-11-01 08:06 UTC, Neill83 commented on src/lib/components/file-browser/file-list/file-list.component.html
> +<mat-toolbar>
hier fehlt noch `<div class="terra-table-container">` drum herum (in Terra gibts da ne Directive dafür, die das macht), ausserdem kannst du `terra-table-toolbar` als class auf `mat-toolbar` machen

dann sollten auch die styles stimmen

2021-11-02 08:56 UTC, niwolf commented
You can change the base-branch to `feature/materialize_file_input_components`

2021-11-02 15:08 UTC, pweyrich approved these changes

2021-11-03 08:51 UTC, Neill83 approved these changes

2021-11-03 09:10 UTC, merged