Added missing tooltips
plentymarkets/terra-components pull request #1668
Opened 2021-11-02 13:22 UTC by adumitrescu-plenty

+ add TooltipDirective to module and to publicApi

@plentymarkets/team-terra

### Definition of Done

#### Must be done by Terra

Testing

-   [ ] Person 1 (mandatory)

    Browser support (relevant for changes in scss / appearance of components)

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

-   [ ] Person 2 (mandatory)

    Browser support

    -   [ ] Chrome
    -   [ ] Firefox
    -   [ ] Safari

    Responsiveness

    -   [ ] Desktop
    -   [ ] Tablet
    -   [ ] Mobile

Information transfer

-   [ ] Inform Team plentyShop about changes in `TerraFormComponent` (optional: relevant for changes in this component)

Terra Basic Plugin

-   [ ] Adapt changes (optional: relevant for version updates, global design changes, l10n)

---

#### Must be done by every developer

Please inform a member of Terra (@plentymarkets/team-terra) to get the upper part of the checklist done (with urgency or deadline).

Documentation

-   [ ] Changelog (optional: relevant for every change which influences the API)
-   [ ] Example (updated or created)
-   [ ] JSDoc (optional: relevant for every change which influences the API)
-   [ ] [Google spreadsheet](https://docs.google.com/spreadsheets/d/1OINnux8TEoitV-qdAxqUQaf9oGI_fqFVwfRWenRFfhI/edit#gid=0) (relevant when deprecating public APIs or features)

Testing

-   [ ] Unit Test (updated or created)

2021-11-02 13:43 UTC, OliverBhm submitted a review, later dismissed

2021-11-02 13:57 UTC, pweyrich commented on src/lib/public-api.ts
> +export { TooltipModule } from './components/tooltip/tooltip.module';
i am not sure if we should add this to the public api

2021-11-03 10:06 UTC, Neill83 approved these changes

2021-11-03 10:23 UTC, Neill83 requested changes
add a changelog

2021-11-03 11:05 UTC, Neill83 requested changes

2021-11-03 11:05 UTC, Neill83 commented on CHANGELOG.md
> +-   **TooltipDirective** added its own module - **TooltipModule**.
```suggestion
-   **tcTooltip** added its own module - **TooltipModule**.
```

2021-11-03 11:39 UTC, pweyrich commented on src/lib/components/tooltip/tooltip.module.ts
> +export class TooltipModule {}
```suggestion
export class TerraTooltipModule {}
```
In order to be consistent with the other exported modules

2021-11-03 11:39 UTC, pweyrich commented on CHANGELOG.md
> +-   **tcTooltip** added its own module - **TooltipModule**.
```suggestion
-   **tooltip** added `TerraTooltipModule` to be able to individually include tooltip functionality.
```

2021-11-04 06:10 UTC, Neill83 requested changes

2021-11-04 06:10 UTC, Neill83 commented on CHANGELOG.md
> +-   **tooltip** added `TerraTooltipModule` to be able to individually include tooltip functionality.
```suggestion
-   **tcTooltip** added `TerraTooltipModule` to be able to individually include tooltip functionality.
```

2021-11-04 06:10 UTC, Neill83 commented on CHANGELOG.md
> +-   **tooltip** added `TerraTooltipModule` to be able to individually include tooltip functionality.
it should be tcTooltip since its the selector of the tooltip and we always use the selector in there somehow...

2021-11-04 08:32 UTC, Neill83 approved these changes

2021-11-04 08:53 UTC, niwolf approved these changes

2021-11-04 08:56 UTC, nappynapster approved these changes

2021-11-04 09:08 UTC, merged